---
title: "Project 3"
author: "Jackson Dial"
date: "11/9/2021"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(lubridate)
library(naniar)
library(flextable)
```


```{r}
#setwd("C:/Users/jacks/OneDrive/Desktop/DUKE_FALL2021/721/BIOSTAT721")
dat18 <- read.csv("Data/data/data/AQ_2018.csv")
dat19 <- read.csv("Data/data/data/AQ_2019.csv")
dat20 <- read.csv("Data/data/data/AQ_2020.csv")
```


```{r}
myfun <- function(data){
  test <- data %>%
    rename(Max8Co = Daily.Max.8.hour.CO.Concentration,
           Mean2.5Pm = Daily.Mean.PM2.5.Concentration,
           Max8Oz = Daily.Max.8.hour.Ozone.Concentration) %>%
    mutate(NewDate = as_date(mdy(Date))) %>%
    group_by(NewDate) %>%
    distinct() %>%
    mutate(Max8Co2 = mean(Max8Co),
           Mean2.5Pm2 = case_when(
             Mean2.5Pm > 0 ~ mean(Mean2.5Pm),
             Mean2.5Pm <= 0 ~ 0),
           Max8Oz2 = mean(Max8Oz)) %>%
    select(Max8Co2, Mean2.5Pm2, Max8Oz2)
    
  MinCoCon <- round(min(test$Max8Co2, na.rm = TRUE),3)
  MaxCoCon <- round(max(test$Max8Co2, na.rm = TRUE),3)
  MinPmCon <- round(min(test$Mean2.5Pm2, na.rm = TRUE),3)
  MaxPmCon <- round(max(test$Mean2.5Pm2, na.rm = TRUE),3)
  MinOzCon <- round(min(test$Max8Oz2, na.rm = TRUE),3)
  MaxOzCon <- round(max(test$Max8Oz2, na.rm = TRUE),3)
  
  Pollutant <- c("Co Concentration", "PM 2.5 Concentration", "Ozone Concentration")
  Max <- c(MaxCoCon, MaxPmCon, MaxOzCon)
  Min <- c(MinCoCon, MinPmCon, MinOzCon)
  
  mytable = cbind.data.frame(Pollutant, Min, Max)
  flextable(mytable)
}

myfun(data = dat18)
myfun(data = dat19)
myfun(data = dat20)
```







